[theme]

# Primary accent for interactive elements
primaryColor = '#93cd36' 

# Background color for the main content area
backgroundColor = '#ffffff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#DAF3FE'

# Color used for almost all text
textColor = '#1C1C1C'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
